-- =============================================================================
-- SECURITY: RBAC, DATA MASKING & GOVERNANCE
-- =============================================================================

USE ROLE SECURITYADMIN;

-- ─── ROLES ─────────────────────────────────────────────────────────────────
CREATE ROLE IF NOT EXISTS DATA_ENGINEER;
CREATE ROLE IF NOT EXISTS DATA_ANALYST;
CREATE ROLE IF NOT EXISTS DATA_SCIENTIST;
CREATE ROLE IF NOT EXISTS BI_USER;
CREATE ROLE IF NOT EXISTS AUDITOR;

-- Role hierarchy
GRANT ROLE DATA_ENGINEER  TO ROLE SYSADMIN;
GRANT ROLE DATA_ANALYST   TO ROLE DATA_ENGINEER;
GRANT ROLE DATA_SCIENTIST TO ROLE DATA_ENGINEER;
GRANT ROLE BI_USER        TO ROLE DATA_ANALYST;
GRANT ROLE AUDITOR        TO ROLE SECURITYADMIN;

-- ─── WAREHOUSE GRANTS ──────────────────────────────────────────────────────
USE ROLE SYSADMIN;
CREATE WAREHOUSE IF NOT EXISTS ETL_WH    WITH WAREHOUSE_SIZE = 'MEDIUM' AUTO_SUSPEND = 120;
CREATE WAREHOUSE IF NOT EXISTS ANALYST_WH WITH WAREHOUSE_SIZE = 'SMALL'  AUTO_SUSPEND = 60;
CREATE WAREHOUSE IF NOT EXISTS BI_WH      WITH WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 60;

USE ROLE SECURITYADMIN;
GRANT USAGE ON WAREHOUSE ETL_WH     TO ROLE DATA_ENGINEER;
GRANT USAGE ON WAREHOUSE ANALYST_WH TO ROLE DATA_ANALYST;
GRANT USAGE ON WAREHOUSE ANALYST_WH TO ROLE DATA_SCIENTIST;
GRANT USAGE ON WAREHOUSE BI_WH      TO ROLE BI_USER;
GRANT USAGE ON WAREHOUSE BI_WH      TO ROLE AUDITOR;

-- ─── DATABASE GRANTS ───────────────────────────────────────────────────────
GRANT USAGE ON DATABASE ECOM_DW TO ROLE DATA_ENGINEER;
GRANT USAGE ON DATABASE ECOM_DW TO ROLE DATA_ANALYST;
GRANT USAGE ON DATABASE ECOM_DW TO ROLE DATA_SCIENTIST;
GRANT USAGE ON DATABASE ECOM_DW TO ROLE BI_USER;
GRANT USAGE ON DATABASE ECOM_DW TO ROLE AUDITOR;

-- STAGE schema: full access to engineers only
GRANT ALL PRIVILEGES ON SCHEMA ECOM_DW.STAGE TO ROLE DATA_ENGINEER;

-- CURATED schema
GRANT USAGE  ON SCHEMA ECOM_DW.CURATED TO ROLE DATA_ANALYST;
GRANT USAGE  ON SCHEMA ECOM_DW.CURATED TO ROLE DATA_SCIENTIST;
GRANT SELECT ON ALL TABLES IN SCHEMA ECOM_DW.CURATED TO ROLE DATA_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA ECOM_DW.CURATED TO ROLE DATA_SCIENTIST;
GRANT SELECT ON ALL TABLES IN SCHEMA ECOM_DW.CURATED TO ROLE AUDITOR;

-- CONSUMPTION schema: BI + analysts read
GRANT USAGE  ON SCHEMA ECOM_DW.CONSUMPTION TO ROLE BI_USER;
GRANT SELECT ON ALL TABLES IN SCHEMA ECOM_DW.CONSUMPTION TO ROLE BI_USER;
GRANT SELECT ON ALL VIEWS  IN SCHEMA ECOM_DW.CONSUMPTION TO ROLE BI_USER;

-- ─── DATA MASKING POLICIES ─────────────────────────────────────────────────
USE ROLE SYSADMIN;
USE SCHEMA ECOM_DW.CURATED;

-- Mask email: analysts see xxx@domain.com, BI sees fully masked
CREATE OR REPLACE MASKING POLICY email_mask AS (val STRING) RETURNS STRING ->
  CASE
    WHEN CURRENT_ROLE() IN ('DATA_ENGINEER','SYSADMIN') THEN val
    WHEN CURRENT_ROLE() = 'DATA_ANALYST'                THEN REGEXP_REPLACE(val, '^[^@]+', '***')
    ELSE '**REDACTED**'
  END;

CREATE OR REPLACE MASKING POLICY phone_mask AS (val STRING) RETURNS STRING ->
  CASE
    WHEN CURRENT_ROLE() IN ('DATA_ENGINEER','SYSADMIN') THEN val
    ELSE CONCAT(LEFT(val,3), '****', RIGHT(val,2))
  END;

CREATE OR REPLACE MASKING POLICY pii_name_mask AS (val STRING) RETURNS STRING ->
  CASE
    WHEN CURRENT_ROLE() IN ('DATA_ENGINEER','SYSADMIN','DATA_ANALYST') THEN val
    ELSE '**REDACTED**'
  END;

-- Apply masking policies
ALTER TABLE DIM_CUSTOMER MODIFY COLUMN email       SET MASKING POLICY email_mask;
ALTER TABLE DIM_CUSTOMER MODIFY COLUMN phone       SET MASKING POLICY phone_mask;
ALTER TABLE DIM_CUSTOMER MODIFY COLUMN first_name  SET MASKING POLICY pii_name_mask;
ALTER TABLE DIM_CUSTOMER MODIFY COLUMN last_name   SET MASKING POLICY pii_name_mask;

-- ─── ROW ACCESS POLICY ─────────────────────────────────────────────────────
-- Region-based row access: BI users only see their region
CREATE OR REPLACE ROW ACCESS POLICY region_access_policy AS (country VARCHAR) RETURNS BOOLEAN ->
  CASE
    WHEN CURRENT_ROLE() IN ('DATA_ENGINEER','DATA_ANALYST','SYSADMIN') THEN TRUE
    WHEN CURRENT_ROLE() = 'BI_USER' THEN country = CURRENT_ACCOUNT_LOCATOR()
    ELSE FALSE
  END;

-- ─── OBJECT TAGGING (Data Governance) ─────────────────────────────────────
USE ROLE ACCOUNTADMIN;
CREATE TAG IF NOT EXISTS PII          ALLOWED_VALUES 'true','false';
CREATE TAG IF NOT EXISTS SENSITIVITY  ALLOWED_VALUES 'PUBLIC','INTERNAL','CONFIDENTIAL','RESTRICTED';
CREATE TAG IF NOT EXISTS DATA_DOMAIN  ALLOWED_VALUES 'customer','product','financial','behavioral';

-- Apply tags
ALTER TABLE ECOM_DW.CURATED.DIM_CUSTOMER  SET TAG PII='true', SENSITIVITY='RESTRICTED',  DATA_DOMAIN='customer';
ALTER TABLE ECOM_DW.CURATED.FACT_PAYMENTS SET TAG PII='false', SENSITIVITY='CONFIDENTIAL', DATA_DOMAIN='financial';
ALTER TABLE ECOM_DW.CURATED.FACT_ORDERS   SET TAG PII='false', SENSITIVITY='INTERNAL',    DATA_DOMAIN='financial';
ALTER TABLE ECOM_DW.CURATED.FACT_CLICKSTREAM SET TAG SENSITIVITY='INTERNAL',              DATA_DOMAIN='behavioral';

-- Column-level PII tags
ALTER TABLE ECOM_DW.CURATED.DIM_CUSTOMER MODIFY COLUMN email SET TAG PII='true';
ALTER TABLE ECOM_DW.CURATED.DIM_CUSTOMER MODIFY COLUMN phone SET TAG PII='true';
ALTER TABLE ECOM_DW.CURATED.DIM_CUSTOMER MODIFY COLUMN date_of_birth SET TAG PII='true';

-- ─── TIME TRAVEL CONFIGURATION ─────────────────────────────────────────────
ALTER TABLE ECOM_DW.CURATED.DIM_CUSTOMER SET DATA_RETENTION_TIME_IN_DAYS = 30;
ALTER TABLE ECOM_DW.CURATED.FACT_ORDERS  SET DATA_RETENTION_TIME_IN_DAYS = 14;
-- Usage: SELECT * FROM DIM_CUSTOMER AT (TIMESTAMP => '2024-01-01 00:00:00'::TIMESTAMP);
-- Usage: SELECT * FROM DIM_CUSTOMER BEFORE (STATEMENT => '<query_id>');
